In [ ]:
# description: to check if a mail is spam(1) or not(0)

In [2]:
#import libraries
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
import string

In [11]:
#reading the data
df = pd.read_csv("emails.csv")

In [12]:
#to get the first 5 rows
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [13]:
df.shape

(5728, 2)

In [14]:
df.columns #to get the column names


Index(['text', 'spam'], dtype='object')

In [15]:
#to check for duplicates
df.drop_duplicates(inplace = True)

In [16]:
df.shape #to get new shape after the duplicates are dropped

(5695, 2)

In [17]:
#show the missing(NAN, NaN or na) data for each column
df.isnull().sum()

text    0
spam    0
dtype: int64

In [29]:
#the above output indicates that we have no missing data
#now we download stopwords package
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [33]:
def process(text):
    #to remove punctuation
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    #to remove stopwords
    clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    #return list of clean words
    return clean_words

In [34]:
df['text'].head().apply(process) #to show tokenization(a list of tokens called lemmas)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [41]:
#example
message4 = 'hello friend hello hello friend play'
message5 = 'test test test test one hello'
print(message4)
print()
#convert the text to a matrix of token counts
#sklearn is ml library
from sklearn.feature_extraction.text import CountVectorizer
bow4 = CountVectorizer(analyzer=process).fit_transform([[message4],[message5]])
print(bow4)
print()
print(bow4.shape) #in this it does not count the worlds which occured already

hello friend hello hello friend play

  (0, 1)	3
  (0, 0)	2
  (0, 3)	1
  (1, 1)	1
  (1, 4)	4
  (1, 2)	1

(2, 5)


In [44]:
#in the above output 0 means msg 4 and 1 is msg 5 it shows number of same words in the message
#we tranform our data into these token counts
from sklearn.feature_extraction.text import CountVectorizer
message_bow = CountVectorizer(analyzer=process).fit_transform(df['text'])
#converts the data into matrix of tokens

In [45]:
# to split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(message_bow, df['spam'], test_size=0.20, random_state=0)   
#x_ is featured data set and y_ is for traget dataset

In [46]:
#get the shape of msg_bow
message_bow.shape

(5695, 37229)

# Naive Bayes Classifier

In [50]:
#create and train naive bayes classifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(x_train, y_train) 
#fit is another name of train

In [52]:
#printing predictions
print(classifier.predict(x_train))
#printing actual values
print(y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [54]:
#to evaluate the model on training dataset
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(x_train)
print(classification_report(y_train, pred))
print()
print('Confusion Matrix: \n', confusion_matrix(y_train, pred))
print()
print('Accuracy:', accuracy_score(y_train, pred)) #that is accuracy in detecting if it spam or not

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


Confusion Matrix: 
 [[3445   12]
 [   1 1098]]

Accuracy: 0.9971466198419666


In [55]:
#printing predictions
print(classifier.predict(x_test))
#printing actual values
print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [56]:
#to evaluate the model on testing dataset
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(x_test)
print(classification_report(y_test, pred))
print()
print('Confusion Matrix: \n', confusion_matrix(y_test, pred))
print()
print('Accuracy:', accuracy_score(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


Confusion Matrix: 
 [[862   8]
 [  1 268]]

Accuracy: 0.9920983318700615
